MvcNetCoreEF/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCoreEF.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int IdEmpleado { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("OFICIO")]
        public string Oficio { get; set; }

        [Column("SALARIO")]
        public int Salario { get; set; }
    }
}

MvcNetCoreEF/Models/ErrorViewModel.cs
namespace MvcNetCoreEF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreEF/Models/Hospital.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCoreEF.Models
{
    [Table("HOSPITAL")]
    public class Hospital
    {
        [Key]
        [Column("HOSPITAL_COD")]
        public int HospitalCod { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("DIRECCION")]
        public string Direccion { get; set; }

        [Column("TELEFONO")]
        public string Telefono { get; set; }

        [Column("NUM_CAMA")]
        public int NumCamas { get; set; }
    }
}

MvcNetCoreEF/Models/ModelEmpleados.cs
namespace MvcNetCoreEF.Models
{
    public class ModelEmpleados
    {
        public List<Empleado> Empleados { get; set; }
        public int SumaSalarial { get; set; }
        public double MediaSalarial { get; set; }
    }
}

MvcNetCoreEF/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreEF.Models;
using MvcNetCoreEF.Repositories;

namespace MvcNetCoreEF.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;

        public EmpleadosController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }

        public IActionResult IncrementoSalarial()
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            return View();
        }

        [HttpPost]
        public IActionResult IncrementoSalarial(int incremento, string oficio)
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            ModelEmpleados model = this.repo.IncrementarSalarioOficio(incremento, oficio);
            return View(model);
        }
    }
}

MvcNetCoreEF/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreEF.Models;
using System.Diagnostics;

namespace MvcNetCoreEF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreEF/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using MvcNetCoreEF.Models;
using MvcNetCoreEF.Repositories;

namespace MvcNetCoreEF.Controllers
{
    public class HospitalesController : Controller
    {
        private RepositoryHospital repo;

        public HospitalesController(RepositoryHospital repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Hospital> hospitales = this.repo.GetHospitales();
            return View(hospitales);
        }

        public IActionResult Details(int id)
        {
            Hospital hospital = this.repo.FindHospital(id);
            return View(hospital);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Hospital hospital)
        {
            this.repo.InsertHospital(hospital);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            this.repo.DeleteHospital(id);
            return RedirectToAction("Index");
        }


        public IActionResult Update(int id)
        {
            Hospital hospital = this.repo.FindHospital(id);
            return View(hospital);
        }

        [HttpPost]
        public IActionResult Update(Hospital hospital)
        {
            this.repo.UpdateHospital(hospital.HospitalCod, hospital.Nombre, hospital.Direccion, hospital.Telefono, hospital.NumCamas);
            return RedirectToAction("Index");
        }
    }
}

MvcNetCoreEF/Views/Empleados/IncrementoSalarial.cshtml
@model ModelEmpleados

@{
    List<string> oficios = ViewData["OFICIOS"] as List<string>;
}

<h1>Incremento Salarial Oficios</h1>

<form method="post" class="mt-3">
    <div class="row">
        <div class="col-6">
            <label class="form-label">Oficio</label>
            <select name="oficio" class="form-select">
                @foreach (string oficio in oficios)
                {
                    <option value="@oficio">@oficio</option>
                }
            </select>
        </div>
        <div class="col-6">
            <label class="form-label">Incremento</label>
            <input type="number" class="form-control" name="incremento" />
        </div>
    </div>
    <button class="btn btn-success w-100 mt-4">Incrementar salarios</button>
</form>

@if (Model is not null)
{
    <div class="row mt-4">
        <div class="col-6">
            <label class="form-label">Suma salarial</label>
            <input type="number" class="form-control" value="@Model.SumaSalarial" readonly />
        </div>
        <div class="col-6">
            <label class="form-label">Media salarial</label>
            <input type="number" class="form-control" value="@Model.MediaSalarial" readonly />
        </div>
    </div>
    <table class="table table-borderless mt-3">
        <thead>
            <tr>
                <th>Apellido</th>
                <th>Oficio</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Empleado emp in Model.Empleados)
            {
                <tr>
                    <td>@emp.Apellido</td>
                    <td>@emp.Oficio</td>
                    <td>@emp.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcNetCoreEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreEF/Views/Hospitales/Create.cshtml
<h1>Crear hospital EF</h1>

<form method="post">
    <div class="mt-3">
        <label class="form-label">Código Hospital</label>
        <input type="number" name="hospitalcod" class="form-control" />
    </div>
    <div class="mt-3">
        <label class="form-label">Nombre</label>
        <input type="text" name="nombre" class="form-control" />
    </div>
    <div class="mt-3">
        <label class="form-label">Dirección</label>
        <input type="text" name="direccion" class="form-control" />
    </div>
    <div class="mt-3">
        <label class="form-label">Teléfono</label>
        <input type="text" name="telefono" class="form-control" />
    </div>
    <div class="mt-3">
        <label class="form-label">Num Camas</label>
        <input type="number" name="numcamas" class="form-control" />
    </div>
    <button class="btn btn-success w-100 mt-3">Crear hospital</button>
</form>

MvcNetCoreEF/Views/Hospitales/Details.cshtml
@model Hospital

<h1>Detalles Hospital EF</h1>
<a asp-controller="Hospitales" asp-action="Index"
   class="btn btn-primary my-3 w-100">
    Volver al Index
</a>

<ul class="list-group">
    <li class="list-group-item">Código: @Model.HospitalCod</li>
    <li class="list-group-item">Nombre: @Model.Nombre</li>
    <li class="list-group-item">Dirección: @Model.Direccion</li>
    <li class="list-group-item">Teléfono: @Model.Telefono</li>
    <li class="list-group-item">Num Camas: @Model.NumCamas</li>
</ul>

MvcNetCoreEF/Views/Hospitales/Index.cshtml
@model List<Hospital>

<h1>Hospitales Entity Framework</h1>

<a asp-controller="Hospitales" asp-action="Create"
   class="btn btn-success w-100 my-3">
    Crear hospital
</a>

<table class="table table-borderless">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (Hospital hospital in Model)
        {
            <tr>
                <td>@hospital.Nombre</td>
                <td>@hospital.Direccion</td>
                <td>@hospital.Telefono</td>
                <td>
                    <a asp-controller="Hospitales" asp-action="Details"
                       asp-route-id="@hospital.HospitalCod" class="btn btn-primary btn-sm">
                        Details
                    </a>
                    <a asp-controller="Hospitales" asp-action="Update"
                       asp-route-id="@hospital.HospitalCod" class="btn btn-warning btn-sm">
                        Update
                    </a>
                    <a asp-controller="Hospitales" asp-action="Delete"
                       asp-route-id="@hospital.HospitalCod" class="btn btn-danger btn-sm">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcNetCoreEF/Views/Hospitales/Update.cshtml
@model Hospital

<h1>Modificar hospital EF</h1>

<a asp-controller="Hospitales" asp-action="Index"
   class="btn btn-primary w-25 my-3">Volver al index</a>

<form method="post">
    <input type="hidden" name="hospitalcod" value="@Model.HospitalCod" />
    <div class="mt-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre" value="@Model.Nombre" />
    </div>
    <div class="mt-3">
        <label class="form-label">Dirección</label>
        <input type="text" class="form-control" name="direccion" value="@Model.Direccion" />
    </div>
    <div class="mt-3">
        <label class="form-label">Teléfono</label>
        <input type="text" class="form-control" name="telefono" value="@Model.Telefono" />
    </div>
    <div class="mt-3">
        <label class="form-label">Num Camas</label>
        <input type="number" class="form-control" name="numcamas" value="@Model.NumCamas" />
    </div>
    <button class="btn btn-warning w-100 mt-3">Modificar hospital</button>
</form>

MvcNetCoreEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreEF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCoreEF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Hospitales" asp-action="Index">Hospitales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Empleados" asp-action="IncrementoSalarial">Empleados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcNetCoreEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>